import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MetaMaskContextProvider } from "@/contexts/useMetaMaskContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import NetworkProvider from "@/components/NetworkProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital Wallet App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NetworkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <MetaMaskContextProvider>{children} </MetaMaskContextProvider>
          </ThemeProvider>
          <Toaster />
        </NetworkProvider>
      </body>
    </html>
  );
}
